apiVersion: apps/v1
kind: Deployment
metadata:
  name: mono-app-deployment
  labels:
    app: mono-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mono-app
  template:
    metadata:
      labels:
        app: mono-app
    spec:
      containers:
        - name: mono-container
          image: 1amteddy/mono-app:latest
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi