apiVersion: v1
kind: Service
metadata:
  name: mono-app-service
  labels:
    app: mono-app
spec:
  selector:
    app: mono-app
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http