name: "Build and Deploy"

on:
  push:
    branches:
      - dev

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Log in to Docker Registry
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and Tag Docker Image
        run: |
          # Build the Docker image
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/my-app:latest .

      - name: Push Docker Image
        run: |
          # Push the Docker image to your Docker Hub repository
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-app:latest

      - name: Deploy with Helm (Reusable Workflow)
        uses: ./.github/workflows/reusable-deploy.yml
        with:
          image_repository: ${{ secrets.DOCKERHUB_USERNAME }}/my-app
          image_tag: latest
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}