name: "Reusable Helm Deploy"

on:
  workflow_call:
    inputs:
      image_repository:
        required: true
      image_tag:
        required: true
    secrets:
      kubernetes_config:
        required: true

jobs:
  helm_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: 'v3.11.3'

      - name: Configure kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.kubernetes_config }}" > $HOME/.kube/config

      - name: Helm Upgrade/Install
        run: |
          helm upgrade --install my-app ./chart \
            --set image.repository=${{ inputs.image_repository }} \
            --set image.tag=${{ inputs.image_tag }}